export const MODULE_CONFIG = [
  {
    id: "dashboard",
    permission: "hr",
    iconKey: "grid",
    labels: { ar: "لوحة التحكم", en: "Dashboard" },
    gradient: "linear-gradient(135deg, #b8946a, #966334)",
  },
  {
    id: "employees",
    permission: "employees",
    iconKey: "users",
    labels: { ar: "الموظفين", en: "Employees" },
    gradient: "linear-gradient(135deg, #7d0a12, #9a1b24)",
  },
  {
    id: "attendance",
    permission: "attendance",
    iconKey: "checkCircle",
    labels: { ar: "الحضور والانصراف", en: "Attendance" },
    gradient: "linear-gradient(135deg, #5a3e2b, #7a5535)",
  },
  {
    id: "leaves",
    permission: "leaves",
    iconKey: "calendar",
    labels: { ar: "الإجازات", en: "Leaves" },
    gradient: "linear-gradient(135deg, #6b2d2d, #8b3e3e)",
  },
  {
    id: "payroll",
    permission: "payroll",
    iconKey: "creditCard",
    labels: { ar: "الرواتب", en: "Payroll" },
    gradient: "linear-gradient(135deg, #966334, #b8946a)",
  },
  {
    id: "recruitment",
    permission: "recruitment",
    iconKey: "activity",
    labels: { ar: "التوظيف", en: "Recruitment" },
    gradient: "linear-gradient(135deg, #4a2020, #7d0a12)",
  },
  {
    id: "performance",
    permission: "performance",
    iconKey: "barChart",
    labels: { ar: "تقييم الأداء", en: "Performance" },
    gradient: "linear-gradient(135deg, #7d0a12, #b8946a)",
  },
  {
    id: "users",
    permission: "users",
    iconKey: "userPlus",
    labels: { ar: "إدارة المستخدمين", en: "Users" },
    gradient: "linear-gradient(135deg, #3a2a1e, #5a3e2b)",
  },
];
